# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('page_view', models.IntegerField(default=0, verbose_name='浏览量')),
                ('article_image', models.ImageField(null=True, upload_to='', verbose_name='文章图片')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 'tb_article',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'tb_comment',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(verbose_name='用户浏览该文章的次数')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '浏览记录',
                'db_table': 'tb_page_view',
                'verbose_name_plural': '浏览记录',
            },
        ),
    ]
