# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181030_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='分类图片'),
        ),
    ]
