# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-30 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_pageviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pageviews',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='pageviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
