# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-31 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181030_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='分类')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '分类标签',
                'verbose_name_plural': '分类标签',
                'db_table': 'tb_category_view',
            },
        ),
    ]
