# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类标签',
                'db_table': 'tb_category_tag',
                'verbose_name_plural': '分类标签',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'tb_tag',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='categorytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='标签'),
        ),
    ]
