# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('describe', models.CharField(max_length=100, verbose_name='描述')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='分类图片')),
            ],
            options={
                'verbose_name': '分类',
                'db_table': 'tb_category',
                'verbose_name_plural': '分类',
            },
        ),
    ]
